name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: master    

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Mod tidy
      run: go mod tidy
      
    - name: Build 
      run: go build -v .

    - name: Test binary
      run: file gocat && ./gocat -help
