---

windows:
  - smss
  - csrss
  - wininit
  - services
  - lsass
  - svchost
  - lsm
  - iexplore
  - acrotray
  - ccSetMgr
  - ctfmon
  - explorer
  - savscan
  - realsched
  - winword
  - winlogon
  - taskmgr
darwin:
  - Documents
  - Downloads
  - Desktop
  - asl.conf
  - hosts
  - chrome
  - libexec
  - trustd
  - cron
  - timed
  - securityd
linux:
  - hosts
  - ntp.conf
  - mnt
  - resolv.conf
  - renice
  - kill
  - pgrep
  - top
  - htop
  - ps
  - pstree
  - rc.common
